name: Deploy Backend

on:
  push:
    branches:
      - main  # Замените на вашу основную ветку, если отличается

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода из репозитория
      - name: Checkout Repository
        uses: actions/checkout@v3

        # Шаг 2: Настройка SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_FRONTEND }}

      # Шаг 3: Выполнение скрипта деплоя бэкенда
      - name: Deploy Backend
        run: |
          ssh -o StrictHostKeyChecking=no root@90.156.156.29 'bash /var/www/life-game-back/deploy-backend.sh'
